S = input()
scales = {
    "WBWBWWBWBWBWWBWBWWBW": "Do",
    "WBWWBWBWBWWBWBWWBWBW": "Re",
    "WWBWBWBWWBWBWWBWBWBW": "Mi",
    "WBWBWBWWBWBWWBWBWBWW": "Fa",
    "WBWBWWBWBWWBWBWBWWBW": "So",
    "WBWWBWBWWBWBWBWWBWBW": "La",
    "WWBWBWWBWBWBWWBWBWWB": "Si",
}
print(scales[S])
